towww:
	tar -zcvf tmp-ko-msg-$(date).tar.gz ./src/library/*/po/*.html
	mv tmp-ko-msg-$(date).tar.gz ../www/msg/standard/
	tar -zxvf ../www/msg/standard/tmp-ko-msg-$(date).tar.gz --directory=../www/msg/standard/
