update:
	rm *.mo
	find ./../src/library/*/po/ -name '*.mo' -exec cp -r {} ./ \;
	cp -ir *.mo $(dir)/
	# R-3.0.0 under the development version (on 2013-MAR-10)
	# R_HOME/src/library/translations/inst/ko/LC_MESSAGES/
	# all .po files should be also updated.

